version: '2'
services:
    hello-docker:
        container_name: "backend"
        build: .
        image: backend-docker
        volumes:
            - /home/producthosts/back-end/public:/tmp
        ports:
            - "3000:3000"
        restart: on-failure

