version: '2'
services:
    hello-docker:
        container_name: "backend"
        image: ghcr.io/violet-evergardenz/int222-backend:latest
        volumes:
            - /home/bluzeadmin/backend/product-images:/tmp/product-images
        ports:
            - "3000:3000"
        restart: on-failure
        networks:
            project2-net:
                ipv4_address: 172.21.0.3
networks:
    default:
        external:
            name: project2-net
#        ipam:
#            config:
#                - subnet: 172.21.0.0/16
#    project2-net:
#        external: true
