name: cicd
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.USER }}
          password: ${{ secrets.AUTHEN_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/violet-evergardenz/int222-backend:latest
  deploy:
    needs: build
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' }}
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOSTNAME }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: | 
          docker pull ghcr.io/violet-evergardenz/int222-backend:latest
          cd backend
          git pull
          docker-compose up -d