name: cicd
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: docker build -t ghcr.io/violet-evergardenz/backend:master .
      - run: docker images
      - run: docker push ghcr.io/violet-evergardenz/backend:master