name: cicd
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: docker build -t ghcr.io/violet-evergardenz/backend:latest .
      - run: docker images
      - run: docker login -u violet-evergardenz -p ${{secrets.AUTHEN_TOKEN}}
      - run: docker push ghcr.io/violet-evergardenz/backend:latest